### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by 89z** [Depado/soundcloud#1]
Is it possible to download audio?

**Comment by Depado** [comment]
If you'd like a simple tool to download audio, you can have a look at [youtube-dl](https://github.com/ytdl-org/youtube-dl) which, despite its name, works great with SC. 
This project is intended to be an API client, so yes, you can download sounds with it, but it will require some work on your part.

**Comment by 89z** [comment]
since no example is available, I wrote my own package:

https://pkg.go.dev/github.com/89z/mech/soundcloud

**Comment by 89z** [comment]
actually I did figure out an example, but looks like the package is broken:

~~~go
package main
import "github.com/Depado/soundcloud"

func main() {
   c, err := soundcloud.NewAutoIDClient()
   if err != nil {
      panic(err)
   }
   if _, err := c.Track().Stream(soundcloud.ProgressiveMP3); err != nil {
      panic(err) // no track assigned or no transcoding found
   }
}
~~~

**Comment by Depado** [comment]
Sorry I think I never really finished working on this package and it's a mess and SoundCloud keeps making breaking change to their API. I'll rework on it as soon as I have some time.

**Comment by 89z** [comment]
If it helps, I have a working alternative here:

https://pkg.go.dev/github.com/89z/mech/soundcloud

**Comment by Depado** [comment]
Nice! I'll have a look, thanks!
